language: node_js
node_js:
  - "17"
script: 'true'
deploy:
  provider: surge
  on:
    branches: master
  project: ./build
  domain: futureworker.cc
after_success:
  - surge --project ./build --domain futureworker.cc
